package com.skybreak.rcwa.domain.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.skybreak.rcwa.domain.event.TextPayloadEventType;
import lombok.Builder;

@DynamoDBTable(tableName = "user_thread_text")
@Builder
public class UserThreadText {
    private String id;
    private TextPayloadEventType type;
    private String data;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public TextPayloadEventType getType() {
        return type;
    }

    @DynamoDBAttribute
    public String getData() {
        return data;
    }
}
